# Generated by Django 4.2.5 on 2023-09-26 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_members_date_members_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='date',
            field=models.DateField(auto_now_add=True, default='2023-6-5'),
            preserve_default=False,
        ),
    ]
