# Generated by Django 4.2.7 on 2023-11-19 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0002_alter_record_creation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='creation_date',
            field=models.DateTimeField(auto_created=True, default=1),
            preserve_default=False,
        ),
    ]
